name: 1.0.0$(Rev:.r)

variables:
  RGPrefix: cd-pu2
  WebAppPrefix: cdpartsun2
  TFDownloadURL: https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip
  RootTFPath: $(System.DefaultWorkingDirectory)/PartsUnlimited-aspnet45/env/tf
  AzureSubscription: 10M Client Demo
  VSTSEndpoint: '10M VSTS'

stages:
- stage: prod_blue
  displayName: Canary Deployment to PROD (blue)
  variables:
  - group: PartsUnlimited Terraform Secrets
  jobs:
  - template: templates/deploy-webapp-job.yml
    parameters:
      environment: PartsUnlimited-PROD
      logicalEnvironment: prod
      slot: blue
      webAppRG: $(RGPrefix)-prod-webapp
      webApp: $(WebAppPrefix)-prod
      azureSub: $(AzureSubscription)
      runQuickPerfTests: no
      vstsEndpoint: $(VSTSEndpoint)
      downloadSteps:
      - download: specific
        project: Demos
        pipelineId: 75
        buildVersionToDownload: $(BuildToDeploy)
        artifact: drop
  
  - template: templates/deploy-and-route-job.yml
    parameters:
      dependsOn: deployWebApp
      environment: PartsUnlimited-PROD
      azureSub: $(AzureSubscription)
      webAppRG: $(RGPrefix)-prod-webapp
      webApp: $(WebAppPrefix)-prod
      runLoadTests: yes
      slot: blue
      percentageToRoute: 20
      downloadSteps:
      - download: specific
        project: Demos
        pipelineId: 75
        buildVersionToDownload: $(BuildToDeploy)
        artifact: drop

- stage: prod_green
  displayName: Full deployment to PROD (green)
  dependsOn: prod_blue
  jobs:
  - template: templates/swap-and-route-job.yml
    parameters:
      environment: PartsUnlimited-PROD
      azureSub: $(AzureSubscription)
      webAppRG: $(RGPrefix)-prod-webapp
      webApp: $(WebAppPrefix)-prod
      vstsEndpoint: $(VSTSEndpoint)
      swapSlots: true
      slot: blue
      percentageToRoute: 0

- stage: prod_rollback
  displayName: Rollback of PROD
  dependsOn: prod_blue
  jobs:
  - template: templates/swap-and-route-job.yml
    parameters:
      environment: PartsUnlimited-PROD
      azureSub: $(AzureSubscription)
      webAppRG: $(RGPrefix)-prod-webapp
      webApp: $(WebAppPrefix)-prod
      swapSlots: false
      slot: blue
      percentageToRoute: 0