trigger:
- master

stages:
- stage: build
  displayName: Build and test sources
  jobs:
  - template: templates/build-job.yml
    parameters:
      packageFeed: ''
      runSonar: '$(runSonar)'
      sonarProjectKey: 'PartsUnlimited'
      sonarUrl: '$(sonarUrl)'
      sonarToken: '$(sonarToken)'

# - stage: dev
#   dependsOn: build
#   jobs:
#   - deployment: deploy_dev
#     displayName: Deploy to Dev
#     pool:
#       vmImage: 'ubuntu-latest'
#     environment: multi-dev
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - script: echo Hello, DEV!
#             displayName: 'Build the source'

# - stage: prod
#   dependsOn: dev
#   jobs:
#   - deployment: deploy_prod
#     displayName: Deploy to Prod
#     pool:
#       vmImage: 'ubuntu-latest'
#     environment: multi-prod
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - script: echo Hello, PROD!
#             displayName: 'Build the source'