name: 1.0.0$(Rev:.r)

variables:
  RGPrefix: cd-pu2
  WebAppPrefix: cdpartsun2

stages:
- stage: build
  displayName: Build and test sources
  jobs:
  - template: templates/build-job.yml
    parameters:
      packageFeed: '7934b660-3831-4640-a3c9-a0fa7aa6d068'
      runSonar: '$(runSonar)'
      sonarProjectKey: 'PartsUnlimited'
      sonarUrl: '$(sonarUrl)'
      sonarToken: '$(sonarToken)'

- stage: dev
  displayName: Deploy to DEV
  dependsOn: build
  variables:
  - group: 'PartsUnlimited Terraform Secrets'
  jobs:
  - template: templates/terraform-job.yml
    parameters:
      armAccessKey: '$(ARMAccessKey)'
      environment: 'PartsUnlimited-DEV'
      rootPath: '$(System.DefaultWorkingDirectory)/PartsUnlimited-aspnet45/env/tf'
      tfDownloadUrl: 'https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip'

  - template: templates/deploy-webapp-job.yml
    parameters:
      environment: 'PartsUnlimited-DEV'
      webAppRG: '$(RGPrefix)-dev-webapp'
      webApp: '$(WebAppPrefix)-dev'
      azureSub: '10M Client Demo'
      runQuickPerfTests: '$(RunQuickPerfTests)'
      vstsEndpoint: '10M VSTS'
  
  - template: templates/run-selenium-job.yml
    parameters:
      baseUrl: 'http://$(WebAppPrefix)-dev.azurewebsites.net'

# - stage: prod
#   dependsOn: dev
#   jobs:
#   - deployment: deploy_prod
#     displayName: Deploy to Prod
#     pool:
#       vmImage: 'ubuntu-latest'
#     environment: multi-prod
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - script: echo Hello, PROD!
#             displayName: 'Build the source'