parameters:
  dependsOn: deployWebApp
  browser: Chrome

jobs:
- job: runSelenium
  dependsOn: ${{ parameters.dependsOn }}
  displayName: Run Selenium Tests
  pool:
    name: CD-ACI
  variables:
    seleniumTestsPath: $(System.DefaultWorkingDirectory)/PartsUnlimited-aspnet45/test/PartsUnlimited.NetCore.SeleniumTests
    BaseUrl: ${{ parameters.baseUrl }}
    Browser: ${{ parameters.browser }}
  steps:
  - checkout: self
    fetchDepth: 1

  - task: UseDotNet@2
    displayName: Use .NET Core sdk 2.1.3
    inputs:
      version: 2.1.3
  
  - task: colinsalmcorner.colinsalmcorner-buildtasks.replace-tokens-task.ReplaceTokens@1
    displayName: Replace tokens in $(seleniumTestsPath)
    inputs:
      sourcePath: $(seleniumTestsPath)'
      filePattern: '*.runsettings'
  
  - script: cat /vsts/agent/_work/1/s/PartsUnlimited-aspnet45/test/PartsUnlimited.NetCore.SeleniumTests/release.runsettings
  
  - task: DotNetCoreCLI@2
    displayName: run dotnet test
    inputs:
      command: test
      projects: $(seleniumTestsPath)/PartsUnlimited.NetCore.SeleniumTests.csproj
      arguments: -s $(seleniumTestsPath)/release.runsettings --logger trx --results-directory $(Agent.TempDirectory)
      publishTestResults: false
    continueOnError: true
  
  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: '**/*.trx'
      searchFolder: $(Agent.TempDirectory)
      testRunTitle: Selenium Tests (${{ parameters.browser }})
    condition: always()
    continueOnError: true