name: Slacker

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Run a one-line script
      run: echo Run a script here!

    - name: Slack notification for Commit
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: github-actions
        SLACK_CHANNEL: partsunlimited
      uses: Ilshidur/action-slack@master
      with:
        args: 'A new ${{ github.event_name }} has been pushed/created by ${{ github.actor }}!'
